import { createContext, useCallback, useEffect, useMemo, useState, type ReactNode } from 'react';
import type { Session } from '@supabase/supabase-js';
import { supabase } from '@/lib/supabase';
import type { SessionUser } from '@/types/domain';

interface AuthContextValue { session:Session|null; user:SessionUser|null; loading:boolean; isAdmin:boolean; signIn:(email:string,password:string)=>Promise<void>; signOut:()=>Promise<void>; refresh:()=>Promise<void>; }
export const AuthContext=createContext<AuthContextValue|null>(null);
interface ProfileRow { id:string; email:string; first_name:string; last_name:string; full_name:string; role:SessionUser['role']; is_active:boolean; employees:{id:string;default_schedule:string;active:boolean;blocked_at:string|null;projects:{name:string}|null}|null; }
async function loadSessionUser(userId:string):Promise<SessionUser|null>{const {data,error}=await supabase.from('profiles').select('id,email,first_name,last_name,full_name,role,is_active,employees:employees!employees_user_id_fkey(id,default_schedule,active,blocked_at,projects:project_id(name))').eq('id',userId).maybeSingle();if(error||!data)return null;const row=data as unknown as ProfileRow;const emp=row.employees;return{id:row.id,email:row.email,firstName:row.first_name,lastName:row.last_name,fullName:row.full_name,role:row.role,isActive:row.is_active && (!emp || (emp.active && !emp.blocked_at)),employeeId:emp?.id??null,project:emp?.projects?.name??null,defaultSchedule:emp?.default_schedule??null};}
export function AuthProvider({children}:{children:ReactNode}){const[session,setSession]=useState<Session|null>(null);const[user,setUser]=useState<SessionUser|null>(null);const[loading,setLoading]=useState(true);const hydrate=useCallback(async(s:Session|null)=>{setSession(s);if(!s?.user){setUser(null);setLoading(false);return;}try{setUser(await loadSessionUser(s.user.id));}catch{setUser(null);}finally{setLoading(false);}},[]);useEffect(()=>{let alive=true;void supabase.auth.getSession().then(({data})=>{if(alive)void hydrate(data.session);});const{data:sub}=supabase.auth.onAuthStateChange((event,s)=>{if(!alive)return;if(event==='TOKEN_REFRESHED'){setSession(s);return;}void hydrate(s);});return()=>{alive=false;sub.subscription.unsubscribe();};},[hydrate]);const signIn=useCallback(async(email:string,password:string)=>{const{error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;},[]);const signOut=useCallback(async()=>{await supabase.auth.signOut();setUser(null);setSession(null);},[]);const refresh=useCallback(async()=>{if(session?.user)setUser(await loadSessionUser(session.user.id));},[session]);const value=useMemo<AuthContextValue>(()=>({session,user,loading,isAdmin:user?.role==='admin',signIn,signOut,refresh}),[session,user,loading,signIn,signOut,refresh]);return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;}
